import { legacyDocument, renderDocument } from './document.js';

const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const relation=(e:any)=>({original:'원본',revision:'개정',fork:'포크',rebuttal:'반박'}[e.relation_kind as string]||'원본')+' v'+(e.version_number||1);
const link=(id:string)=>'/chat?exploration='+encodeURIComponent(id);
export const blogStyle=`<style>.blog-actions{display:flex;gap:12px;flex-wrap:wrap;margin:22px 0}.blog-actions a{text-decoration:none;font:600 14px system-ui;display:inline-block}.blog-tags{display:flex;gap:8px;flex-wrap:wrap;font:12px system-ui;color:var(--accent);margin-bottom:12px}.blog-tag{background:#e8eddf;border-radius:5px;padding:4px 7px}.blog-intro{font:15px/1.9 system-ui;color:var(--muted)}.blog-stats{display:flex;gap:24px;flex-wrap:wrap;font:14px system-ui;border-top:1px solid var(--line);padding:20px 0}.blog-stats b{display:block;font-size:26px;color:var(--accent);margin-bottom:6px}.blog-group h2{font:700 20px system-ui;margin:35px 0 18px}.blog-empty{padding:30px;border:1px dashed var(--line);border-radius:14px;color:var(--muted)}.blog-document{font:17px/1.95 system-ui;overflow-wrap:anywhere}.blog-document h2{font:36px/1.35 Georgia,serif}.blog-document h3{font:27px/1.4 Georgia,serif;margin-top:36px}.blog-document p{white-space:pre-wrap}.blog-document pre{white-space:pre-wrap;background:#ecefe5;padding:16px;border-radius:9px}.blog-document blockquote{border-left:3px solid #93a888;margin-left:0;padding-left:20px;color:var(--muted)}.blog-lineage{font:14px/1.8 system-ui}.blog-lineage a{display:block;padding:7px 0}.blog-transcript .msg{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.8 system-ui}@media(max-width:600px){.top{height:auto;min-height:70px;gap:15px;flex-wrap:wrap;padding:16px 0}.nav{display:flex;gap:15px;flex-wrap:wrap}.nav a{margin-left:0;font-size:12px}.hero{padding-top:42px}.hero h1{font-size:36px;line-height:1.2}.lede{font-size:18px}.card{padding:20px}.card h2{font-size:23px}.profile h1{font-size:32px}}</style>`;

export function blogCard(e:any,privateView=false){
  const href=privateView?link(e.id):'/@'+encodeURIComponent(e.username)+'/'+encodeURIComponent(e.slug);
  const excerpt=e.document_body?e.document_body.replace(/^#.*\n?/,'').replace(/[#*`>]/g,'').trim().slice(0,180):e.opening_question;
  return `<a class="card" href="${href}"><div class="blog-tags"><span class="blog-tag">${esc(e.topic==='general'?'일반':e.topic||'일반')}</span><span>${esc(relation(e))}</span>${privateView?'<span>'+ (e.status==='published'?'공개':'비공개')+'</span>':''}</div><h2>${esc(e.title)}</h2><p class="blog-intro">${esc(excerpt)}</p><div class="meta">@${esc(e.username)} · AI와 함께 쓴 지식${e.support_points!==undefined?' · 지지 '+Number(e.support_points).toLocaleString()+'P':''}</div></a>`;
}

export function blogHome(u:any,items:any[],own=false,conversations:any[]=[],wallet?:any){
  const groups=new Map<string,any[]>();for(const e of items){const topic=e.topic&&e.topic!=='general'?e.topic:'일반';groups.set(topic,[...(groups.get(topic)||[]),e]);}
  return blogStyle+`<section class="profile"><div class="kicker">${own?'MY KNOWLEDGE BLOG':'CO-CREATED WITH AI'}</div><h1>${esc(u.display_name)}의 지식 블로그</h1><p class="blog-intro">@${esc(u.username)} · ${esc(u.bio||'AI와 대화하며 만들고, 다른 관점으로 이어가는 지식.')}</p><div class="blog-actions"><a class="btn" href="/chat">${own?'새 주제 함께 쓰기':'주제와 대화 둘러보기'} →</a>${own?'<a href="/@'+encodeURIComponent(u.username)+'">공개 블로그 보기 ↗</a>':''}</div></section>`+
    (own&&wallet?`<div class="blog-stats"><span><b>${items.filter(e=>e.status==='published').length}</b>발행한 글·버전</span><span><b>${wallet.balance.toLocaleString()}P</b>사용 가능한 포인트</span><span><b>${wallet.supported.toLocaleString()}P</b>누적 지지 투자</span><span><b>${wallet.earned.toLocaleString()}P</b>받은 포인트</span></div><p class="meta">무료 포인트로 관심과 지지를 표현합니다. 구매·현금화·금전적 가치는 없습니다.</p>`:'')+
    (own&&conversations.length?`<section class="blog-group"><h2>이어서 작성하기</h2>${conversations.map(c=>'<a class="card" href="/chat?conversation='+encodeURIComponent(c.id)+'"><div class="meta">작성 중 · 비공개</div><h2>'+esc(c.title)+'</h2></a>').join('')}</section>`:'')+
    [...groups].map(([topic,list])=>`<section class="blog-group"><h2>${esc(topic)} <span class="meta">${list.length}개 글·버전</span></h2>${list.map(e=>blogCard(e,own)).join('')}</section>`).join('')+
    (!items.length?'<p class="blog-empty">'+(own?'아직 저장한 글·버전이 없습니다. 대화로 문서를 만든 뒤 버전을 저장해 보세요.':'아직 공개된 글이 없습니다.')+'</p>':'');
}

export function publishedArticle(e:any,msgs:any[],lineage:any[],support:any){
  return blogStyle+`<article><section class="hero"><div class="kicker">KNOWLEDGE CO-CREATED WITH AI</div><h1>${esc(e.title)}</h1><p class="meta"><a href="/@${encodeURIComponent(e.username)}">${esc(e.display_name)} · @${esc(e.username)}</a> · ${esc(relation(e))} · ${esc(e.topic==='general'?'일반':e.topic)}</p><div class="blog-actions"><a class="btn" href="${link(e.id)}">대화·문서 함께 읽고 이어 쓰기 →</a><a href="${link(e.id)}">포인트로 지지하기 · ${support.total.toLocaleString()}P / ${support.supporters}명</a></div></section><div class="blog-document">${renderDocument(legacyDocument(e))}</div><section class="section blog-lineage"><h3>이어진 생각과 버전</h3>${lineage.filter(n=>n.id!==e.id).map(n=>'<a href="'+link(n.id)+'">'+(n.id===e.parent_id?'↖ 이어받은 원문':'↳ 이어진 글')+' · '+esc(relation(n))+' · '+esc(n.title)+' / @'+esc(n.username)+'</a>').join('')||'<p class="blog-intro">포크, 개정, 반박으로 이 글에 새로운 관점을 더할 수 있습니다.</p>'}</section><details class="blog-transcript"><summary>이 문서를 만든 원문 대화 · ${msgs.length}개 메시지</summary>${msgs.map(m=>'<div class="msg"><div class="role">'+esc(m.role==='user'?'작성자':'AI')+'</div>'+esc(m.content)+'</div>').join('')||'<p>저장된 원문 대화가 없습니다.</p>'}</details></article>`;
}
